GridLogikViewer/Controllers/AlarmLogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GridLogik.ViewModels;
using System.Net;
using Newtonsoft.Json;
using System.Web.Configuration;
using System.Web.UI.WebControls;
using System.IO;
using System.Web.UI;
using System.Net.Http;
using System.Threading.Tasks;
using GridLogikViewer.Filters;

namespace GridLogikViewer.Controllers
{
     [Authorize]
    public class AlarmLogController : Controller
    {
        string _uri = WebConfigurationManager.AppSettings["APIUrl"];
        string uri = string.Empty;
        
        //
        // GET: /AlarmLog/
         [AccessCheck(IdParamName = "AlarmLog/Index")]
        public async Task<ActionResult> Index()
        {
            ViewBag.Message = TempData["Message"];
            ViewBag.Status = TempData["Status"];
            ViewBag.InnerMessage = TempData["InnerMessage"];

            //var data = ViewData.Model as MstRoleMenuAccess;
            //if (data.rmacreateaccess == 0)
            //    ViewBag.CreateAccess = "False";
            //if (data.rmadeleteaccess == 0)
            //    ViewBag.DeleteAccess = "False";
            //if (data.rmaupdateaccess == 0)
            //    ViewBag.EditAccess = "False";

            IEnumerable<HTAlarm> htalarmobj;
            HTAlarm obj = new HTAlarm();
            obj.fltrFromDate = DateTime.Now.ToString("MM'/'dd'/'yyyy");
            obj.fltrToDate = DateTime.Now.ToString("MM'/'dd'/'yyyy");
            obj.AllChecked = "All";
            using (HttpClient client = new HttpClient())
            {
                uri = string.Format("{0}AlarmLog/PostAlarmLog", _uri);

                var result = await client.PostAsJsonAsync(uri, obj);

                htalarmobj = await result.Content.ReadAsAsync<IEnumerable<HTAlarm>>();

                TempData["AlarmLogList"] = htalarmobj;
            }

            return View(htalarmobj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(HTAlarm h)
        {
            IEnumerable<HTAlarm> htalarmobj;
            using (HttpClient client = new HttpClient())
            {
                uri = string.Format("{0}AlarmLog/filter", _uri);

                var result = await client.PostAsJsonAsync(uri, h);

                htalarmobj = await result.Content.ReadAsAsync<IEnumerable<HTAlarm>>();
                TempData["AlarmLogList"] = htalarmobj;
            }
            return View("Index", htalarmobj);
        }
        public async Task<ActionResult> Export(HTAlarm model)
        {
            

            //IEnumerable<HTAlarm> alarmlog;

            //using (HttpClient client = new HttpClient())
            //{
            //    url = string.Format("{0}AlarmLog/filter", _uri);
            //    var result = await client.PostAsJsonAsync(url, model);
            //    alarmlog = await result.Content.ReadAsAsync<IEnumerable<HTAlarm>>();
            //    TempData["AlarmLogList"] = alarmlog;
            //}


            ////using (WebClient client = new WebClient())
            ////{
            ////    client.Headers.Add("Content-Type", "application/json");
            ////    string s = client.UploadString(url + "AlarmLogAPI/filter", "POSt", JsonConvert.SerializeObject(model));
            ////    alarmlog = JsonConvert.DeserializeObject<List<HTAlarm>>(s);
            ////    TempData["AlarmLogList"] = alarmlog;
            ////}

            //var grid = new GridView();
            //var reducedList = alarmlog.Select(e => new { e.ID, e.alarmname, e.alarmmessage, e.metername, e.starttimelog, e.stoptimelog }).ToList();
            //grid.DataSource = reducedList;
            //grid.DataBind();
            //grid.HeaderRow.Cells[0].Text = "ID";
            //grid.HeaderRow.Cells[1].Text = "Alarm Name";
            //grid.HeaderRow.Cells[2].Text = "Alarm Message";
            //grid.HeaderRow.Cells[3].Text = "Meter Name";
            //grid.HeaderRow.Cells[4].Text = "Start Time";
            //grid.HeaderRow.Cells[5].Text = "End Time";
            
            //Response.ClearContent();
            //Response.AddHeader("content-disposition", "attachment; filename=alarmlog_" + DateTime.Now.ToString("yyyyMMdd_HHmm") + ".xls");
            //Response.ContentType = "application/excel";
            //StringWriter sw = new StringWriter();
            //HtmlTextWriter htw = new HtmlTextWriter(sw);
            //grid.RenderControl(htw);
            //HttpContext.Response.AddHeader("content-disposition", "attachment; filename=AlarmLog_" + DateTime.Now.Day.ToString() + "_" + DateTime.Now.Month.ToString() + "_" + DateTime.Now.Year.ToString() + "_" + DateTime.Now.Hour.ToString() + "" + DateTime.Now.Minute.ToString() + ".xls");
            //this.Response.ContentType = "application/vnd.ms-excel";
            //byte[] temp = System.Text.Encoding.UTF8.GetBytes(htw.InnerWriter.ToString().Replace("<div>", "").Replace("</div>", ""));//
            //grid.Dispose();
            //htw.Dispose();
            
            //Response.Write(sw.ToString());
            //Response.End();
            //return File(temp, "application/vnd.ms-excel");

            IEnumerable<HTAlarm> alarmlog;

            using (HttpClient client = new HttpClient())
            {
                uri = string.Format("{0}AlarmLog/filter", _uri);
                var result = await client.PostAsJsonAsync(uri, model);
                alarmlog = await result.Content.ReadAsAsync<IEnumerable<HTAlarm>>();
                TempData["AlarmLogList"] = alarmlog;
            }



            var reducedList = alarmlog.Select(e => new { e.ID, e.alarmname, e.alarmmessage, e.metername, e.starttimelog, e.stoptimelog }).ToList();
           
            var grid = new GridView();

            grid.DataSource = reducedList;
            grid.DataBind();
            grid.HeaderRow.Cells[0].Text = "ID";
            grid.HeaderRow.Cells[1].Text = "Alarm Name";
            grid.HeaderRow.Cells[2].Text = "Alarm Message";
            grid.HeaderRow.Cells[3].Text = "Meter Name";
            grid.HeaderRow.Cells[4].Text = "Start Time";
            grid.HeaderRow.Cells[5].Text = "End Time";

            StringWriter sw = new StringWriter();
            HtmlTextWriter htw = new HtmlTextWriter(sw);
            grid.RenderControl(htw);
            HttpContext.Response.AddHeader("content-disposition", "attachment; filename=AlarmLog_" + DateTime.Now.Day.ToString() + "_" + DateTime.Now.Month.ToString() + "_" + DateTime.Now.Year.ToString() + "_" + DateTime.Now.Hour.ToString() + "" + DateTime.Now.Minute.ToString() + ".xls");
            this.Response.ContentType = "application/vnd.ms-excel";
            byte[] temp = System.Text.Encoding.UTF8.GetBytes(htw.InnerWriter.ToString().Replace("<div>", "").Replace("</div>", ""));//
            grid.Dispose();
            htw.Dispose();
            return File(temp, "application/vnd.ms-excel");


        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> updateall(List<HTAlarm> sd)
        {

            try
            {

                using (HttpClient client = new HttpClient())
                {
                    uri = string.Format("{0}AlarmLog/updateall", _uri);
                    var result = await client.PostAsJsonAsync(uri, sd);

                    return Json(new { Message = "Records updated successfully" }, JsonRequestBehavior.AllowGet);
                }

                //using (WebClient web = new WebClient())
                //{
                //    web.Headers.Add("Content-Type", "application/json");
                //    string status = web.UploadString(url + "AlarmLogAPI/updateallvalue", JsonConvert.SerializeObject(sd));
                //    //ViewBag.Msg = "Records updated successfully";

                //    return Json(new { Message = "Records updated successfully" }, JsonRequestBehavior.AllowGet);
                //}
            }
            catch (Exception)
            {
                return Json(new { Message = "Unable to proceed. Please try again later." }, JsonRequestBehavior.AllowGet);
                //throw;
            }


            //   return View("Index");





            //return View();

        }
    }
}

GridLogikViewer/Views/AlarmLog/Index.cshtml
@model IEnumerable<GridLogik.ViewModels.HTAlarm>
@{
    ViewBag.Title = "";
}
<section>
    <div id="main-content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <!--Top header start-->
                    @*<h3 class="ls-top-header col-md-6">
                            Alarm Log
                        </h3>*@
                    <!--Top header end -->
                    <!--Top breadcrumb start -->
                    <ol class="breadcrumb col-md-12 text-left bgn">
                        <li><a href="#"><i class="fa fa-home"></i></a></li>
                        <li><a href="#">Logs</a></li>
                        <li class="active">Alarm Log</li>
                    </ol>
                    <!--Top breadcrumb start -->

                    <div class="row  mb55">
                        <div class="col-md-12">
                            <!--Table Wrapper Start-->
                            <hr />
                            <div class="panel panel-light-blue">
                                @*<div class="panel-heading">
                                    <span class="pull-left">
                                        <strong>
                                            Alarm Log
                                        </strong>
                                    </span>
                                    <div class="clearfix"></div>
                                </div>*@
                                <div class="panel-body">
                                    @using (Html.BeginForm("Index", "AlarmLog"))
                                    {
                                        @Html.AntiForgeryToken()
                                        <div class="row mb5">
                                            <div class="col-md-4">
                                                <div class="row mt20">
                                                    <div class="col-md-4 text-right">
                                                        <label><strong> From Date	 </strong></label>
                                                    </div>
                                                    <div class="col-md-8">
                                                        @Html.TextBoxFor(model => model.FirstOrDefault().fltrFromDate, new { @id = "FromDate", @class = "form-control", @readonly = true, @name = "txtFrmDate" })
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="col-md-4">
                                                <div class="row mt20">
                                                    <div class="col-md-4 text-right">
                                                        <label><strong> To Date	 </strong></label>
                                                    </div>
                                                    <div class="col-md-8">
                                                        @Html.TextBoxFor(model => model.LastOrDefault().fltrToDate, new { @id = "toDate", @class = "form-control", @readonly = true, @name = "txtFrmDate" })
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-4">
                                                <div class="row mt20">
                                                    <div class="col-md-6">
                                                        &nbsp;&nbsp; @Html.RadioButtonFor(m => m.LastOrDefault().AllChecked, "All", new { Checked = "checked" }) Active&nbsp;&nbsp;
                                                        @Html.RadioButtonFor(m => m.LastOrDefault().AllChecked, "Offline") History
                                                        @*@Html.RadioButton("Status", "1", new { @ID = "Statused", @name = "Status" }) Offline*@
                                                    </div>
                                                    <div class="col-md-6 text-left">
                                                        <input type="submit" value="Filter" class="btn btn-warning" id="btnRefresh" onclick="filter()" />
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row mb5">
                                            <div class="col-md-12">
                                                <hr />

                                                <div class="table-responsive ls-table">

                                                    <table class="table table-bordered table-striped" id="lsttable">
                                                        <thead>
                                                            <tr>
                                                                <th class="text-center">ID</th>
                                                                <th class="text-center">Alarm Name</th>
                                                                <th class="text-center">Alarm Message</th>
                                                                <th class="text-center">Meter Name</th>
                                                                <th class="text-center">Start Time</th>
                                                                <th class="text-center">End Time</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody id="filterdata">
                                                            @foreach (var item in Model)
                                                            {
                                                                <tr>
                                                                    <td class="text-center">
                                                                        @Html.DisplayFor(modelItem => item.ID)

                                                                    </td>
                                                                    <td class="text-center">

                                                                        @Html.DisplayFor(modelItem => item.alarmname)
                                                                    </td>
                                                                    <td class="text-center">
                                                                        @Html.DisplayFor(modelItem => item.alarmmessage)
                                                                    </td>
                                                                    <td class="text-center">
                                                                        @Html.DisplayFor(modelItem => item.metername)
                                                                    </td>
                                                                    <td class="text-center">
                                                                        @Html.DisplayFor(modelItem => item.starttimelog)
                                                                    </td>
                                                                    <td class="text-center">
                                                                        @Html.DisplayFor(modelItem => item.stoptimelog)
                                                                    </td>
                                                                </tr>
                                                            }
                                                        </tbody>
                                                    </table>
                                                    <br />
                                                        <button type="button" class="btn btn-success btn-sm" id="export"><i class="fa fa-file-excel-o"></i> Export to Excel</button><div class="clearfix"></div>
                                                </div>
                                            </div>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>






<script>

    $(document).ready(function () {
        //  debugger;
        $("#FromDate,#toDate").datepicker({
            dateFormat: $("#DateField").val(),
            changeMonth: true,
            changeYear: true,
            maxDate: '0'

        }).datepicker('setDate', new Date());


        // iterate  through each row of your table
        //$('#lsttable tr').each(function () {
        //    debugger;

        //    var IsChecked = $(this).find('.chcktbl').prop("checked")
        //    if (IsChecked) {
        //        $(this).find('.chcktbl').attr('disabled', true);
        //        $(this).css('background', '#5cb85c');

        //    }
        //    else {
        //        $(this).css('background', '#e74c3c');
        //    }
        //});
        //$('#lsttable #chckHead').click(function () {
        //    debugger;


        //    if (this.checked == false) {

        //        $('.chcktbl:checked').not(':disabled').prop('checked', false);

        //    }
        //    else {
        //        $('.chcktbl:not(:checked)').prop('checked', true);

        //    }


        //});



        @*$('#export').click(function () {
            box = new ajaxLoader(this, { classOveride: 'blue-loader', bgColor: '#000' });
            var actionUrl = '@Url.Action("Export", "AlarmLog")';
            window.open("Export");
            if (box) box.remove();
        });*@

        $('#export').click(function () {
            box = new ajaxLoader(this, { classOveride: 'blue-loader', bgColor: '#000' });
            var tblRowCount = $('#lsttable tr').length;
            var fltrFromDate = $("#FromDate").val();
            var fltrToDate = $("#toDate").val();
            var AllChecked = $("input[name='AllChecked']:checked").val();

            var obj = { "fltrFromDate": fltrFromDate, "fltrToDate": fltrToDate };
            if (tblRowCount > 2) {
                debugger;
                window.location.href = "@Url.Action("Export", "AlarmLog")?Page=data&fltrFromDate=" + fltrFromDate + "&fltrToDate=" + fltrToDate + "&AllChecked=" + AllChecked;
            }
            else {
                if (box) box.remove();
                alert('No Records Found for Excel Generation', '', false, 'E');
                return false;
            }
            if (box) box.remove();
        });


        $("#lsttable").dataTable(
                 {
                     pageLength: 10,
                     "aoColumns": [null,
                                      null,
                                    null,
                                     null,
                                       null,
                                    { "bSortable": false, "searchable": false, "width": "144px" }
                     ],
                 });
    });



    function myfunction() {

        var i = 0;
        var TableData = new Array();

        $('#lsttable tr').each(function (row, tr) {
            if (row != 0) {
                debugger;
                var IsChecked = $(this).find('.chcktbl').prop("checked")
                var Isdisabled = $(this).find('.chcktbl').prop("disabled")
                if (IsChecked && Isdisabled == false) {
                    TableData[i] = {
                        "ID": $(tr).find('td:eq(0)').text()
                        , "ISMANUALACK": $(tr).find('.chcktbl').prop("checked")

                    }
                    i++;
                }

            }

        });



        $.ajax({

            type: "Post",
            contentType: "application/json;charset=utf-8",

            url: BaseAddress +"/AlarmLog/updateall",
            data: JSON.stringify(TableData),
            dataType: "json",
            success: function (menus, status, jqXHR) {
                alert(menus.Message, '@Url.Action("Index")', false, 'S');
                '@Url.Action("Index")';
            },
            error: function (xhr, status, error) {
                //alert(error);

            }
        });

    }
</script>