GridLogikViewer/Areas/ILFS/Controllers/DCSGController.cs
using GridLogikViewer.Areas.ABTScreen;
using GridLogikViewer.Areas.ABTScreen.Models;
using GridLogikViewer.GridLogikViewerModels;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Configuration;
using System.Web.Hosting;
using System.Web.Mvc;

namespace GridLogikViewer.Areas.ILFS.Controllers
{
    public class DCSGController : Controller
    {
        string url = WebConfigurationManager.AppSettings["APIUrl"];
        //string Message, MessageType = "";


        //////[HttpPost]
        //////public ActionResult CheckUpload(FormCollection formCollection)
        //////{
        //////    string Jsonstr;
        //////    using (WebClient client = new WebClient())
        //////    {
        //////        client.Headers.Add("Content-Type", "application/json");

        //////        Jsonstr = client.UploadString(url + "DCSGAPI/CheckUpload", JsonConvert.SerializeObject(Convert.ToDateTime(formCollection[2])));
        //////        dynamic dynamicDCSG = JValue.Parse(Jsonstr);

        //////        TempData["Msg"] = dynamicDCSG.Data.d;
        //////        TempData["MsgType"] = dynamicDCSG.Data.e;
        //////        return View();

        //////    }
        //////    return View();
        //////}

        [HttpPost]
        public ActionResult Upload(FormCollection formCollection)
        {
            try
            {
                if (Request != null)
                {
                    HttpPostedFileBase file = Request.Files["Uploadfile"];
                    List<dcsg> list = new List<dcsg>();
                    if ((file != null) && (file.ContentLength > 0) && !string.IsNullOrEmpty(file.FileName))
                    {
                        string fileName = file.FileName;
                        string fileContentType = file.ContentType;
                        byte[] fileBytes = new byte[file.ContentLength];
                        var data = file.InputStream.Read(fileBytes, 0, Convert.ToInt32(file.ContentLength));

                        using (var package = new ExcelPackage(file.InputStream))
                        {
                            var currentSheet = package.Workbook.Worksheets;
                            var workSheet = currentSheet.First();
                            var noOfCol = workSheet.Dimension.End.Column;
                            var noOfRow = workSheet.Dimension.End.Row;

                            for (int rowIterator = 2; rowIterator <= noOfRow; rowIterator++)
                            {
                                dcsg dcsg = new dcsg();
                                dcsg.blockno = Convert.ToInt32(workSheet.Cells[rowIterator, 1].Value.ToString());
                                dcsg.sgvalue = Convert.ToDecimal(workSheet.Cells[rowIterator, 2].Value.ToString());
                                dcsg.dcvalue = Convert.ToDecimal(workSheet.Cells[rowIterator, 3].Value.ToString());
                                dcsg.fuelcost = Convert.ToDecimal(workSheet.Cells[rowIterator, 4].Value.ToString());

                                string startdate = GetFinaldate(formCollection["txtFrmDate"], Request.Form["ServerDateformat"].ToString(), Request.Form["Dateformat"].ToString());
                                //string enddate = GetFinaldate(mtrf.enddate, Request.Form["ServerDateformat"].ToString(), Request.Form["Dateformat"].ToString());

                                dcsg.tstamp = DateTime.ParseExact(formCollection["txtFrmDate"], "dd/MM/yyyy", System.Globalization.CultureInfo.InvariantCulture);// Convert.ToDateTime(startdate); // DateTime.ParseExact(formCollection["txtFrmDate"], "dd/MM/yyyy", System.Globalization.CultureInfo.InvariantCulture);// Convert.ToDateTime(formCollection["txtFrmDate"]);
                                dcsg.stageid = Convert.ToInt64(workSheet.Cells[rowIterator, 5].Value.ToString());// Convert.ToInt32(formCollection["txtstageid"]);
                                dcsg.revision = Convert.ToInt32(formCollection["txtrevisionid"]);
                                list.Add(dcsg);
                            }
                        }
                        if (list.Count > 0 && list != null)
                        {
                            string Jsonstr;

                            using (WebClient client = new WebClient())
                            {
                                client.Headers.Add("Content-Type", "application/json");
                                Jsonstr = client.UploadString(url + "DCSGAPI", JsonConvert.SerializeObject(list));
                                dynamic dynamicDCSG = JValue.Parse(Jsonstr);

                                TempData["Msg"] = dynamicDCSG.Data.d;
                                TempData["MsgType"] = dynamicDCSG.Data.e;
                                return View();

                            }
                        }
                        else
                        {

                            MessageList objMsg = MessageRepository.GetMessage("13021", null);
                            TempData["Msg"] = objMsg.Msg_Text;
                            TempData["MsgType"] = objMsg.Msg_Type;
                            return View();
                        }
                    }
                    else
                    {
                        MessageList objMsg = MessageRepository.GetMessage("13021", null);
                        TempData["Msg"] = objMsg.Msg_Text;
                        TempData["MsgType"] = objMsg.Msg_Type;
                        return View();
                    }

                }
                else
                {
                    MessageList objMsg = MessageRepository.GetMessage("13022", null);
                    TempData["Msg"] = objMsg.Msg_Text;
                    TempData["MsgType"] = objMsg.Msg_Type;
                    return View();
                }
            }
            catch (Exception ex)
            {
                MessageList objMsg = MessageRepository.GetMessage("13023", null);
                TempData["Msg"] = objMsg.Msg_Text;
                TempData["MsgType"] = objMsg.Msg_Type;
                new clsExceptionRepository().DBErrorLog(ex.Message, ex.StackTrace, this.ControllerContext.RouteData.Values["controller"].ToString());
                return View();
            }

        }
        public FileResult Download(string id)
        {
            try
            {
                string FileName = GetFileName();
                return File(FileName, System.Web.MimeMapping.GetMimeMapping(FileName), "DCSG.xlsx");
            }
            catch (Exception ex)
            {
                new clsExceptionRepository().DBErrorLog(ex.Message, ex.StackTrace, this.ControllerContext.RouteData.Values["controller"].ToString());
                return null;
            }
        }
        public string GetFileName()
        {
            DirectoryInfo dirInfo = new DirectoryInfo(HostingEnvironment.MapPath("~/Template"));
            return dirInfo.FullName + @"\" + "DCSG.xlsx";
        }

        public ActionResult Upload()
        {
            return View();
        }

        protected string GetFinaldate(string textdate, string DBDateFormat, string Dateformat)
        {
            string[] dateAr = textdate.Split('/');
            var finalDate = textdate;
            if (DBDateFormat == "dd/mm/yy" && Dateformat == "mm/dd/yy")
            {
                finalDate = dateAr[1] + '-' + dateAr[0] + '-' + dateAr[2];
            }
            else if (DBDateFormat == "mm/dd/yy" && Dateformat == "dd/mm/yy")
            {
                finalDate = dateAr[1] + '-' + dateAr[0] + '-' + dateAr[2];
            }
            return finalDate;
        }

        protected string GetClientdate(string textdate, string DBDateFormat)
        {
            var finalDate = textdate;

            if (textdate != null && textdate != "")
            {
                var dateAr = textdate.Split('-');

                if (DBDateFormat == "dd/mm/yy")
                {
                    finalDate = dateAr[2] + '-' + dateAr[1] + '-' + dateAr[0];
                }
                else if (DBDateFormat == "mm/dd/yy")
                {
                    finalDate = dateAr[1] + '-' + dateAr[2] + '-' + dateAr[0];
                }
            }
            return finalDate;
        }
    }
}

GridLogikViewer/Areas/ILFS/Controllers/ILFSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;

namespace GridLogikViewer.Areas.ILFS.Controllers
{
    public class ILFSController : Controller
    {
        string url = WebConfigurationManager.AppSettings["APIUrl"];

        public ActionResult ABTUnit1()
        {
            return View("ABTUnit1");
        }
        public ActionResult ABTUnit2()
        {
            return View("ABTUnit2");
        }
        public ActionResult Station()
        {
            return View("Station");
        }
        public ActionResult Unit1Block()
        {
            return View("Unit1Block");
        }
        public ActionResult Unit2Block()
        {
            return View("Unit2Block");
        }
        public ActionResult Calculate()
        {
            return View("Unit2Block");
        }
        public ActionResult SLD()
        {
            return View("SLD");
        }
        public ActionResult One()
        {
            return View("One");
        }
        public ActionResult Two()
        {
            return View("Two");
        }
        public ActionResult Three()
        {
            return View("Three");
        }
        public ActionResult Four()
        {
            return View("Four");
        }
        public ActionResult Five()
        {
            return View("Five");
        }
        public ActionResult Six()
        {
            return View("Six");
        }
        public ActionResult Seven()
        {
            return View("Seven");
        }
    }
}

GridLogikViewer/Areas/KRAHEJA/Controllers/SLDController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GridLogikViewer.Areas.KRAHEJA.Controllers
{
    public class SLDController : Controller
    {
        //
        // GET: /KRAHEJA/SLD/
        public ActionResult SLD_GEPL()
        {
            return View();
        }
        public ActionResult SLD_MBPL()
        {
            return View();
        }
        public ActionResult SLD_MBPL_Table()
        {
            return View();
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Index1()
        {
            return View();
        }
        public ActionResult Index2()
        {
            return View();
        }
        public ActionResult Index3()
        {
            return View();
        }

        public ActionResult Index4()
        {
            return View();
        }

        public ActionResult Index5()
        {
            return View();
        }

        public ActionResult Index6()
        {
            return View();
        }

        public ActionResult Index7()
        {
            return View();
        }

        public ActionResult Index8()
        {
            return View();
        }
        public ActionResult Index9()
        {
            return View();
        }

        public ActionResult Index10()
        {
            return View();
        }

        public ActionResult Index11()
        {
            return View();
        }
        public ActionResult Index12()
        {
            return View();
        }

        public ActionResult Index13()
        {
            return View();
        }

        public ActionResult Index14()
        {
            return View();
        }

        public ActionResult Index15()
        {
            return View();
        }

        public ActionResult Index16()
        {
            return View();
        }

        public ActionResult Index17()
        {
            return View();
        }

        public ActionResult Index18()
        {
            return View();
        }

        public ActionResult Index19()
        {
            return View();
        }

        public ActionResult Index20()
        {
            return View();
        }

        public ActionResult Index21()
        {
            return View();
        }

        public ActionResult Index22()
        {
            return View();
        }
        public ActionResult Index23()
        {
            return View();
        }
        public ActionResult Index24()
        {
            return View();
        }

        public ActionResult Index25()
        {
            return View();
        }
        public ActionResult Index26()
        {
            return View();
        }

        public ActionResult Index27()
        {
            return View();
        }

        public ActionResult Index28()
        {
            return View();
        }

        public ActionResult Index29()
        {
            return View();
        }

        public ActionResult Index30()
        {
            return View();
        }





	}
}

GridLogikViewer/Areas/ILFS/Views/ILFS/SLD.cshtml
@model List<EToolsViewer.APIModels.GetInstanceData>
@{
    Layout = "~/Views/Shared/_EToolsLayout1.cshtml";
}
<script src="~/Scripts/moment.js"></script>
<style>
    .table-style_01 th, .table-style_01 td {
        background: #2f2f2f !important;
        color: #17bab8;
        font-size: 16px;
        text-align: center;
    }

    .table-style_02 th, .table-style_02 td {
        background: #2f2f2f !important;
        color: #ed9979;
        font-size: 16px;
        text-align: center;
    }

    .table-style_03 th, .table-style_03 td {
        background: #2f2f2f !important;
        color: #f02d99;
        font-size: 16px;
        text-align: center;
    }

    .table-style_04 th, .table-style_04 td {
        background: #2f2f2f !important;
        color: #ebd504;
        font-size: 16px;
        text-align: center;
    }

    .table-style_05 th, .table-style_05 td {
        background: #2f2f2f !important;
        color: #00adef;
        font-size: 16px;
        text-align: center;
    }

    .table-style_06 th, .table-style_06 td {
        background: #2f2f2f !important;
        color: #83c338;
        font-size: 16px;
        text-align: center;
    }

    .table-hover_01 > tbody > tr:hover > td, .table-hover_01 > tbody > tr:hover > th {
        background-color: #f00 !important;
    }

    .panel-default > .panel-heading {
        padding: 2px 10px;
    }

    .bgimg {
        background-image: url('../Content/images/SLD.png');
    }
</style>
<div class="col-lg-12">

    <div class="form-group col-md-4" style="border:0px solid #f00;">
        <h1>PLANT SLD</h1>

    </div>

</div>
<br />
@*background-image: url(/Content/images/SLD1.png); background-size: 100px 100px*@
@*kunal new abt*@
<div class="row">
    <div class="col-lg-12" style="border: 0px solid #000;">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class=" dashboard-panel-body-box" style="font-size:25px; font-weight:bold;"><h3 id="datetidvalue" style="color: lightgreen;"></h3></div>

            </div>
            <div style=" height: 960px; width: 1340px; border: 0px solid #000; background-image: url(/Content/images/Drawing10.png);">

                <button type="button" style="position: absolute; top: 193px; left: 290px;background-color: #ADD8E6;border: 6px; width: 183px; font-size: 25px; color:maroon ; margin:0px 10px;" id="btn1"></button>
                <button type="button" style="position: absolute; top: 193px; left: 935px;background-color: #ADD8E6;border: 6px; width: 183px; font-size: 25px; color:maroon ; margin:0px 10px;" id="btn2"></button>
                <button type="button" style="position: absolute; top: 385px; left: 290px;background-color: #ADD8E6;border: 6px; width: 183px; font-size: 25px; color:maroon ; margin:0px 10px;" id="btn3"></button>
                <button type="button" style="position: absolute; top: 385px; left: 935px;background-color: #ADD8E6;border: 6px; width: 183px; font-size: 25px; color:maroon ; margin:0px 10px;" id="btn4"></button>
                <button type="button" style="position: absolute; top: 385px; left: 602px;background-color: #ADD8E6;border: 6px; width: 183px; font-size: 25px; color:maroon; margin:0px 10px;" id="btn5"></button>
                <button type="button" style="position: absolute; top: 630px; left: 290px;background-color: #ADD8E6;border: 6px; width: 183px; font-size: 25px; color:maroon; margin:0px 10px;" id="btn6"></button>
                <button type="button" style="position: absolute; top: 630px; left: 935px;background-color: #ADD8E6;border: 6px; width: 183px; font-size: 25px; color:maroon; margin:0px 10px;" id="btn7"></button>
                <label id="m1" style="position: absolute; top:285px; left: 410px; width: 100%; font-size: 25px; color: maroon">0.00KV</label>
                <label id="m2" style="position: absolute; top:285px; left: 1050px; width: 100%; font-size: 25px; color: maroon">0.00KV</label>
                <label id="m3" style="position: absolute; top:285px; left: 680px; width: 100%; font-size: 25px; color: maroon"></label>
                <label id="m4" style="position: absolute; top: 560px; left: 410px; width: 100%; font-size: 25px; color: maroon; ">0.00KV</label>
                <label id="m5" style="position: absolute; top: 560px; left: 1050px; width: 100%; font-size: 25px; color: maroon; ">0.00KV</label>




            </div>
        </div>

    </div>

    <script type="text/javascript">
        var ws, w1, w2;
        var meterId = "";
        var box;
        var MeterString = "1,2,3,4,5,6,7";
        var MeterIdList = {
            "MeterString": MeterString

        };
        var ConfingArr = new Array();
        $(document).ready(function () {
            $("#btn1").click(function () {
                box = new ajaxLoader(this, { classOveride: 'blue-loader', bgColor: '#000' });
                window.location.href = '@Url.Action("One", "ILFS")';
            });
            $("#btn2").click(function () {
                box = new ajaxLoader(this, { classOveride: 'blue-loader', bgColor: '#000' });
                window.location.href = '@Url.Action("Two", "ILFS")';
            });
            $("#btn3").click(function () {
                box = new ajaxLoader(this, { classOveride: 'blue-loader', bgColor: '#000' });
                window.location.href = '@Url.Action("Three", "ILFS")';
            });
            $("#btn4").click(function () {
                box = new ajaxLoader(this, { classOveride: 'blue-loader', bgColor: '#000' });
                window.location.href = '@Url.Action("Four", "ILFS")';
            });
            $("#btn5").click(function () {
                box = new ajaxLoader(this, { classOveride: 'blue-loader', bgColor: '#000' });
                window.location.href = '@Url.Action("Five", "ILFS")';
            });
            $("#btn6").click(function () {
                box = new ajaxLoader(this, { classOveride: 'blue-loader', bgColor: '#000' });
                window.location.href = '@Url.Action("Six", "ILFS")';
            });
            $("#btn7").click(function () {
                box = new ajaxLoader(this, { classOveride: 'blue-loader', bgColor: '#000' });
                window.location.href = '@Url.Action("Seven", "ILFS")';
            });
            ABTMeterDetails();
        });




        @*$("#btnBack").click(function () {
        box = new ajaxLoader(this, { classOveride: 'blue-loader', bgColor: '#000' });
        window.location.href = '@Url.Action("Index", "EMSMeter")';
    });*@
        setInterval(ABTMeterDetails, 1000);
        function ABTMeterDetails() {

            $.ajax({

                type: "POST",
                url: BaseAddress + "GetAllInstanceData/",
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(MeterIdList),
                dataType: "json",

                success: function (response, status, jqXHR) {

                    var jsonObj = response.Data.result;
                    debugger
                    if (jsonObj != undefined && jsonObj.length > 0) {
                        debugger
                        var line1hz = 0, line2hz = 0;
                        jsonObj.forEach(function (responseobj) {
                            if (responseobj.meterid == 1) {

                                $("#btn1").html(responseobj.kw.toFixed(2).toString()+ "MW");
                                $("#m1").html(responseobj.vll.toFixed(2).toString() + "KV");
                                line1hz = responseobj.cblk_avg_hz.toFixed(2);

                            }
                            else if (responseobj.meterid == 2) {

                                $("#btn2").html(responseobj.kw.toFixed(2).toString()+ "MW");
                                $("#m2").html(responseobj.vll.toFixed(2).toString() + "KV");
                                line2hz = responseobj.cblk_avg_hz.toFixed(2);
                            }
                            else if (responseobj.meterid == 3) {

                                $("#btn3").html(responseobj.kw.toFixed(2).toString()+ "MW");

                            }
                            else if (responseobj.meterid == 4) {

                                $("#btn4").html(responseobj.kw.toFixed(2).toString()+ "MW");

                            }
                            else if (responseobj.meterid == 5) {

                                $("#btn5").html(responseobj.kw.toFixed(2).toString()+ "MW");
                            }
                            else if (responseobj.meterid == 6) {
                                $("#m4").html(responseobj.vll.toFixed(2).toString() + "KV");
                                $("#btn6").html(responseobj.kw.toFixed(2).toString()+ "MW");
                            }
                            else if (responseobj.meterid == 7) {

                                $("#btn7").html(responseobj.kw.toFixed(2).toString()+ "MW");
                                $("#m5").html(responseobj.vll.toFixed(2).toString() + "KV");
                            }
                            var d = new Date(responseobj.Currenttstamp);
                            var month = (d.getMonth() + 1).toString();
                            if (month.toString().length == 1) {
                                month = "0" + month;
                            }
                            var hours = d.getHours().toString();
                            if (hours.length == 1) {
                                hours = "0" + hours;
                            }
                            var minutes = d.getMinutes().toString();
                            if (minutes.length == 1) {
                                minutes = "0" + minutes;
                            }
                            var seconds = d.getSeconds().toString();
                            if (seconds.length == 1) {
                                seconds = "0" + seconds;
                            }
                            var date = d.getDate() + "-" + month + "-" + d.getFullYear() + "  ;  " + hours + ":" + minutes + ":" + seconds;

                            $("#datetidvalue").text("Date & Time : " + date.toString() + '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0' + " Block No. : " + responseobj.BlockNo);
                        });
                        if (line1hz > line2hz) {
                            $("#m3").html(line1hz.toString() + "Hz");
                        }
                        else {
                            $("#m3").html(line2hz.toString() + "Hz");
                        }

                    }
                },
                error: function (xhr, status, error) {
                    if (box) box.remove();
                }
            });

        }

    </script>